import datetime

def generate_markdown_report(parsed_email, result, vt_results=None, output_path="report.md"):
    now = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    content = f"""# 🛡️ Phishing Detection Report

**Generated:** {now}

---

## 📨 Email Summary

- **From:** {parsed_email['from']}
- **To:** {parsed_email['to']}
- **Subject:** {parsed_email['subject']}

### ✉️ Body Preview:
{parsed_email['body'][:500]}...

### 🔗 Links Found:
"""
    if parsed_email['links']:
        for link in parsed_email['links']:
            content += f"- {link}\n"
            if vt_results and link in vt_results:
                score = vt_results[link]
                if "error" in score:
                    content += f"  - ⚠️ VirusTotal: {score['error']}\n"
                else:
                    content += (
                        f"  - ✅ Harmless: {score['harmless']} | "
                        f"⚠️ Suspicious: {score['suspicious']} | "
                        f"❌ Malicious: {score['malicious']}\n"
                    )
    else:
        content += "- No links found\n"

    content += f"""

---

## 🧠 Analysis

- **Risk Score:** {result['score']} / 100
- **Label:** {result['label'].upper()}

### ⚠️ Flags Detected:
{chr(10).join(f"- {flag}" for flag in result['flags']) or '- None'}

---

*Report generated by Austin Deering's Phishing Detection Tool.*
"""

    with open(output_path, "w", encoding="utf-8") as f:
        f.write(content)
    return output_path
